name       : qt5-webkit
version    : 5.212.0_2
release    : 19
source     :
    - https://github.com/annulen/webkit/releases/download/qtwebkit-5.212.0-alpha2/qtwebkit-5.212.0-alpha2.tar.xz : f8f901de567e11fc5659402b6b827eac75505ff9c5072d8e919aa306003f8f8a
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 support for Webkit
description: |
    Qt5 support for Webkit
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-fft-1.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - gperf
    - hyphen-devel
    - leveldb-devel
    - ruby
setup      : |
    %apply_patches
    %cmake -DPORT=Qt \
           -DENABLE_TOOLS=OFF
build      : |
    %make
install    : |
    %make_install
