name       : qt5-webkit
version    : 5.212.0_3
release    : 24
source     :
    - https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha3/qtwebkit-5.212.0-alpha3.tar.xz : 357eee582445574472e410ebece632d06fa0ec94358fc4345f2a713922df5e17
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 support for Webkit
description: |
    Qt5 support for Webkit
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-fft-1.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2common)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - gperf
    - hyphen-devel
    - leveldb-devel
    - ruby
setup      : |
    %apply_patches
    %cmake_ninja -DPORT=Qt \
           -DENABLE_TOOLS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
