name       : qt5-webkit
version    : 5.7.0
release    : 1
source     :
    - http://download.qt.io/community_releases/5.7/5.7.0/qtwebkit-opensource-src-5.7.0.tar.xz : c7a3253cbf8e6035c54c3b08d8a9457bd82efbce71d4b363c8f753fd07bd34df
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 support for Webkit
description: |
    Qt5 support for Webkit
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Core)
    - pkgconfig(sqlite3)
    - pkgconfig(libpng)
    - pkgconfig(libxml-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - gperf
    - ruby
    - libjpeg-turbo-devel
setup      : |
    qmake QMAKE_CFLAGS_ISYSTEM=-I WebKit.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
