name       : qt5-webkit
version    : 5.6.1
release    : 2
source     :
    - http://download.qt.io/community_releases/5.6/5.6.1/qtwebkit-opensource-src-5.6.1.tar.gz : f5ba5afc5846fc755575dd04081a90a9536f920e312f18f6fb1f5a0c33f477b0
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 support for Webkit
description: |
    Qt5 support for Webkit
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Core)
    - pkgconfig(sqlite3)
    - pkgconfig(libpng)
    - pkgconfig(libxml-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - gperf
    - ruby
    - libjpeg-turbo-devel
setup      : |
    qmake QMAKE_CFLAGS_ISYSTEM=-I WebKit.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
