name       : qt5-webkit
version    : 5.9.1
release    : 8
source     :
    - https://download.qt.io/official_releases/qt/5.9/5.9.1/submodules/qtwebkit-opensource-src-5.9.1.tar.xz : 28a560becd800a4229bfac317c2e5407cd3cc95308bc4c3ca90dba2577b052cf
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 support for Webkit
description: |
    Qt5 support for Webkit
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(sqlite3)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - gperf
    - leveldb-devel
    - libjpeg-turbo-devel
    - ruby
setup      : |
    %qmake QMAKE_CFLAGS_ISYSTEM=-I WebKit.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
