name       : qt5-webkit
version    : 5.9.0
release    : 5
source     :
    - http://download.qt.io/community_releases/5.9/5.9.0-final/qtwebkit-opensource-src-5.9.0.tar.xz : 8dad193b740055a998312e04a040f2e32a923c0823b2d239b24eab08276a4e04
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 support for Webkit
description: |
    Qt5 support for Webkit
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(sqlite3)
    - pkgconfig(libpng)
    - pkgconfig(libxml-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - gperf
    - leveldb-devel
    - libjpeg-turbo-devel
    - ruby
setup      : |
    %qmake QMAKE_CFLAGS_ISYSTEM=-I WebKit.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
